title: Sseoni's gitblog
description: AI, MLOps, LLM, ProductManager, Engineer
url: "https://sseoni.github.io"
baseurl: ""
encoding: "utf-8"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:categories/:title/