title: Sseoni's gitblog
description: AI, MLOps, LLM, ProductManager, Engineer
url: "https://sseoni.github.io"
baseurl: ""
encoding: "utf-8"

defaults:
  - scope:
      path: "_posts/ai-ml/00-Intro"
      type: "posts"
    values:
      categories: ["ai-ml", "00-Intro"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/ai-ml/01-ai-foundations"
      type: "posts"
    values:
      categories: ["ai-ml", "01-ai-foundations"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/ai-ml/02-classical-ml"
      type: "posts"
    values:
      categories: ["ai-ml", "02-classical-ml"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/ai-ml/03-deep-learning"
      type: "posts"
    values:
      categories: ["ai-ml", "03-deep-learning"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/ai-ml/04-llm-genai"
      type: "posts"
    values:
      categories: ["ai-ml", "04-llm-genai"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/ai-ml/05-ml-engineering"
      type: "posts"
    values:
      categories: ["ai-ml", "05-ml-engineering"]
      permalink: /blog/:categories/:title/




  - scope:
      path: "_posts/cs/langchain"
      type: "posts"
    values:
      categories: ["cs", "langchain"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/cs/python"
      type: "posts"
    values:
      categories: ["cs", "python"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/cs/docker"
      type: "posts"
    values:
      categories: ["cs", "docker"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/cs/aws"
      type: "posts"
    values:
      categories: ["cs", "aws"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/cs/error-handling"
      type: "posts"
    values:
      categories: ["cs", "error-handling"]
      permalink: /blog/:categories/:title/




  - scope:
      path: "_posts/paper-review"
      type: "posts"
    values:
      categories: ["paper-review"]
      permalink: /blog/:categories/:title/




  - scope:
      path: "_posts/experiences/projects"
      type: "posts"
    values:
      categories: ["experiences", "projects"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/experiences/educations"
      type: "posts"
    values:
      categories: ["experiences", "educations"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/experiences/engagements"
      type: "posts"
    values:
      categories: ["experiences", "engagements"]
      permalink: /blog/:categories/:title/




  - scope:
      path: "_posts/beyond-code/insights"
      type: "posts"
    values:
      categories: ["beyond-code", "insights"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/beyond-code/personal-moments"
      type: "posts"
    values:
      categories: ["beyond-code", "personal-moments"]
      permalink: /blog/:categories/:title/