title: Sseoni's gitblog
description: AI, MLOps, LLM, ProductManager, Engineer
url: "https://sseoni.github.io"
baseurl: ""
encoding: "utf-8"

defaults:
  - scope:
      path: "_posts/ai-research/ai-foundations"
      type: "posts"
    values:
      categories: ["ai-research", "ai-foundations"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/ai-research/ai-ml"
      type: "posts"
    values:
      categories: ["ai-research", "ai-ml"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/ai-research/llm"
      type: "posts"
    values:
      categories: ["ai-research", "llm"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/ai-research/paper-review"
      type: "posts"
    values:
      categories: ["ai-research", "paper-review"]
      permalink: /blog/:categories/:title/




  - scope:
      path: "_posts/engineering/python"
      type: "posts"
    values:
      categories: ["engineering", "python"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/engineering/langchain"
      type: "posts"
    values:
      categories: ["engineering", "langchain"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/engineering/mlops"
      type: "posts"
    values:
      categories: ["engineering", "mlops"]
      permalink: /blog/:categories/:title/




  - scope:
      path: "_posts/workspace/projects"
      type: "posts"
    values:
      categories: ["workspace", "projects"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/workspace/dev-log"
      type: "posts"
    values:
      categories: ["workspace", "dev-log"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/workspace/retrospectives"
      type: "posts"
    values:
      categories: ["workspace", "retrospectives"]
      permalink: /blog/:categories/:title/




  - scope:
      path: "_posts/beyond-code/insights"
      type: "posts"
    values:
      categories: ["beyond-code", "insights"]
      permalink: /blog/:categories/:title/

  - scope:
      path: "_posts/beyond-code/personal"
      type: "posts"
    values:
      categories: ["beyond-code", "personal"]
      permalink: /blog/:categories/:title/